service:
  postgres:
    # IMAGE
    image: postgres:16
    # CONTAINER
    container_name: postgres
    # ENV
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # MAPPING PORT
    ports:
      - "5432:5432"
    # MAPPING VOLUME
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_PASSWORD}']
      interval: 5s
      timeout: 3s
      retries: 30